#pragma once

#include <hedley.h>

#define IR_FORCEINLINE HEDLEY_ALWAYS_INLINE
#define IR_NOINLINE HEDLEY_NEVER_INLINE
#define IR_LIKELY HEDLEY_LIKELY
#define IR_UNLIKELY HEDLEY_UNLIKELY
#define IR_ASSUME HEDLEY_ASSUME